### ISSUE TITLE
Call to riak_repl_wm_stats:jsonify_stats fails during fullsync

### ISSUE THREAD

**Issue by fprimex** [basho/riak_ee-issues#1]
When a fullsync is running, calls to riak_repl_wm_stats:jsonify_stats will fail with e.g.

{error,{error,function_clause,[{riak_repl_wm_stats,jsonify_stats,[[{fullsync,63,left},...

This is called during webmachine calls to '/riak-repl/stats'.

**Comment by bookshelfdave** [comment]
When reporting the "number of partitions remaining" appears in the raw stats, there is a pattern matching error converting a tuple like `{fullsync, #partitions, left}` into standard JSON. A patch has been generated against 1.2.1 and 1.3, but will need to be tested and certified before release. This bug only affects JSON output of statistics.

**Comment by bookshelfdave** [comment]
Fixed in repl master.
