### ISSUE TITLE
/riak-repl/stats returns last_fullsync_started as byte array

### ISSUE THREAD

**Issue by cipy** [basho/riak_ee-issues#16]
Hi,

http://localhost:8098/riak-repl/stats returns `last_fullsync_started` as a string of bytes (see below) instead of the more human readable: <<"Mon, 05 May 2014 07:37:55 GMT">>

Thanks,
Ciprian

```
     "last_fullsync_started" : [
        77,
        111,
        110,
        44,
        32,
        48,
        53,
        32,
        77,
        97,
        121,
        32,
        50,
        48,
        49,
        52,
        32,
        48,
        55,
        58,
        51,
        55,
        58,
        53,
        53,
        32,
        71,
        77,
        84
     ],
```

**Comment by cipy** [comment]
- `last_fullsync_started` is not mentioned in the official documentation http://docs.basho.com/riakee/1.4.8/cookbooks/Multi-Data-Center-Replication-Statistics/#Fullsync-Replication-Statistics, while the documented `fullsync_start_time` does not exist in the actual `riak-repl` output.

**Comment by cmeiklejohn** [comment]
Resolved.
