### ISSUE TITLE
Evaluate possibility to copy tombstoned objects during fullsync replication

### ISSUE THREAD

**Issue by jonasrichard** [basho/riak_ee-issues#21]
It would be good to have a configuration option with which one can specify if the fullsync replication replicates the tombstoned objects from source to sink.

It is clear that fullsync replication cannot remove data from sink side because if we have two clusters and both of them are used with some load balancer, some objects will be only on the first cluster and some will be only on the second cluster. So if fullsync deletes objects from sink side which aren't in the source side, it can delete data which can be important.

However if one deletes an object (puts a tombstone on that object) while the object lives in the source cluster, fullsync can safely copy that object with tombstone to the sink cluster. Depending on the `delete_mode` the object will be deleted physically later. In that way deleted objects (or object deletion) can be replicated with fullsync replication.

Right now in case of only fullsync replication clusters cannot be kept in sync (in case of realtime replication object deletes can be dropped in extreme cases). So with that option and the delete_mode option one can configure Riak in a way that it can solve this object delete problem.

Please investigate if it helps and it is worth implementing that.

**Comment by jonmeredith** [comment]
The way the current system is implemented is that the tombstone is sent over the wire, and after the sink side write, if it spots that the object is a tombstone, it triggers a get which reaps the object.  Both sides should obey their local delete_mode settings. 

For this to work right, the tombstone would have to exist long enough on the source cluster for a fullsync to complete after it is written.  The safe way to do this is to set with delete_mode=keep, but that means that Riak will never remove the tombstone from the underlying KV store.  You can set delete_mode to run on a timer, but that does have some performance impacts when you have many deletes active (it grows the number of entries in the timer wheel of the ErlangVM).

There are a few other edge cases around MDC deletion and tombstone collection.  We're addressing some of them with basho/riak_kv#679 against 2.0 and we are also looking at changing the way we do tombstone removal by introducing some additional metadata into Riak and MDC to track when all replicas have seen tombstones and are safe to remove them.

Does the explanation above explain the behavior you are seeing?  If not, could you provide the delete_mode settings on both sides and an example flow of client operations and fullsyncs, with what you expect to happen and the behavior you see please.

**Comment by jonmeredith** [comment]
Getting some additional information from @roooms, will update soon.

**Comment by jonmeredith** [comment]
Just verified it works as I described.  The issue that tripped us up was you cannot set delete_mode from the console (without restarting internal processes), you have to add it to app.config file and restart the node.

**Comment by jonasrichard** [comment]
Ok @jonmeredith we can close this ticket, since it works as expected.
