### ISSUE TITLE
Stats error when no leader is set

### ISSUE THREAD

**Issue by alexmoore** [basho/riak_ee-issues#22]
If replication gets into a state where `riak_repl2_leader:leader_node().` returns `undefined`, you get the following stats error (from Riak EE 2.0.2):

```
RPC to 'NODE' failed: {'EXIT',
                       {function_clause,
                        [{lists,foldl,
                          [#Fun<riak_repl_console.45.1073848>,
                           0,
                           {[],[]}],
                          [{file,"lists.erl"},
                           {line,1247}]},
                         {riak_repl_console,
                          sum_fs_kbps,2,
                          [{file,
                            "src/riak_repl_console.erl"},
                           {line,991}]},
                         {riak_repl_console,
                          extract_rt_fs_send_recv_kbps,
                          1,
                          [{file,
                            "src/riak_repl_console.erl"},
                           {line,690}]},
                         {riak_repl_console,
                          status2,1,
                          [{file,
                            "src/riak_repl_console.erl"},
                           {line,155}]},
                         {rpc,
                          '-handle_call_call/6-fun-0-',
                          5,
                          [{file,"rpc.erl"},
                           {line,205}]}]}}

```

You can replicate this locally by starting an EE cluster, attaching to Riak, executing `riak_repl2_leader:set_candidates([],[]).`, and polling the stats with `riak-repl status`. 

The issue is that `riak_repl_console` is expecting `[]` status back when the leader is undefined, but `riak_repl2_fscoordinator_serv` actually returns `{[],[]}`.

[repl_console - Line expecting an empty list](https://github.com/basho/riak_repl/blob/2.0.2/src/riak_repl_console.erl#L991)
[repl_console - call to riak_repl2_fscoordinator_serv:status()](https://github.com/basho/riak_repl/blob/2.0.2/src/riak_repl_console.erl#L904-L909)
[riak_repl2_fscoordinator_serv:status()](https://github.com/basho/riak_repl/blob/2.0.2/src/riak_repl2_fscoordinator_serv.erl#L50-L54])

**Comment by DSomogyi** [comment]
Comment for Jira.

**Comment by engelsanchez** [comment]
This should have been fixed by https://github.com/basho/riak_repl/pull/645
