### ISSUE TITLE
Memory Leak in riak_core_connection_mgr_stats

### ISSUE THREAD

**Issue by ian-mi** [basho/riak_ee-issues#26]
Whenever there is a connection error, riak_core_connection_mgr_stats will create or update a stat which includes the entire error. When the error tuple includes unique information such as PIDs or Port Ids, this causes new folsom statistics be created with each error creating a memory leak. See [riak_repl issue #771](https://github.com/basho/riak_repl/issues/711).

**Comment by JeetKunDoug** [comment]
Fixed by https://github.com/basho/riak_repl/pull/716
