### ISSUE TITLE
Add cascading replication to BNW and(if possible) old repl

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_ee-issues#3]
We have many customers who would like to have real time replication move data through data-centers in a cascading fashion. Example:

DC1 <----> DC2 -----> DC3

DC1 <----> DC2 (DC1 to DC2 is bi-directional replication)

DC2 -----> DC3 (DC2 to DC3 one way replication).

When we add keys to DC1 we want them to replicate to DC2 AND DC3.

**Comment by bookshelfdave** [comment]
Tracking internally at: https://github.com/basho/riak_repl/issues/167

**Comment by angrycub** [comment]
This has been merged into 1.4
