### ISSUE TITLE
riak-repl status fullsync_coordinator successful_exits off by 1

### ISSUE THREAD

**Issue by jcapricebasho** [basho/riak_ee-issues#6]
The successful_exits metric of the fullsync_coordinator in riak-repl status is ring_creation_size - 1 when no errors are reported.

**Comment by slfritchie** [comment]
This issue can be closed, perhaps?  It isn't clear to me why Chris reopened it.

**Comment by jcapricebasho** [comment]
Closing issue - fixed was merged into master and shipped with 1.4.
