### ISSUE TITLE
`riak-repl start-fullsync` does nothing on non-leader node

### ISSUE THREAD

**Issue by angrycub** [basho/riak_ee-issues#8]
Running `riak-repl start-fullsync` on a node in the cluster that is not the replication leader results in no messages and no actions. Preferable behavior would be to either communicate with the leader to start a fullsync, or return a message stating that no action is being taken and that the command should be run on the leader (and/or log the message).

**Comment by cmeiklejohn** [comment]
Closing as we are tracking in riak_repl.
